[package]
authors = ["Daan Rijks <daanrijks@gmail.com>"]
name = "teslabot"
version = "0.1.0"

[dependencies]
discord = { version = "0.8.0", default-features = false }
lazy_static = "0.2.8"
rand = "0.3.15"
